application: pickempickem
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on
- mapreduce: on
- deferred: on

handlers:
- url: /static
  static_dir: static
  secure: optional

- url: /(favicon\.ico|robots\.txt|crossdomain\.xml|opensearch\.xml)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt|crossdomain\.xml|opensearch\.xml)

- url: /data/.*
  script: data/main.py
  login: admin

- url: .*
  script: main.py
